### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by digitaldonkey** [kornrunner/php-keccak#2]
Hi, 

is there any chance you gonna dual license that? 
I'm writing a GPL Drupal module and a Ethereum-PHP library. 
Sadly the later one must be MIT as much as I love GPL licenses. 
Any chance you might change/Dual license your code?

Or is it legal to use GPL3 in a MIT project?
I'm totally confused now --> https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

**Comment by kornrunner** [comment]
Switched to MIT in https://github.com/kornrunner/php-keccak/commit/c0838c34822a52cc27b3dcf48b8c3b08a084fd3f

Cheers!
