### ISSUE TITLE
hash_hmac  function supports the sha3 alogorithm since PHP 7.1+

### ISSUE THREAD

**Issue by peter279k** [kornrunner/php-keccak#5]
As title, the `hash_hmac` function supports the `sha-3` algorithms since `PHP 7.1`.

I think it should be better than using this PHP package and this should support before `PHP 7.1` version.

See more details about [this](http://php.net/manual/en/function.hash-algos.php).

Thanks.

**Comment by kornrunner** [comment]
There's a minor difference between `keccak` (which is used by Ethereum) and `sha-3` (that actually got accepted by FIPS) in a padding constant used by algorithm.

Thus, two of them are different, and produce different output for the same input:

```php
<?php

require_once 'vendor/autoload.php';

use kornrunner\Keccak;

echo Keccak::hash('', 256) . PHP_EOL;
// c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470

echo hash('sha3-256', '') . PHP_EOL;
// a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a
```

**Comment by peter279k** [comment]
@kornrunner, thank you for your explanation.

Now I realize the difference of these `sha-3` implementation approach and this is for the `ETH`.

I will close this issue and thank you for your explanation again :+1: !
