### ISSUE TITLE
wrong result after keccak256 hash of a string

### ISSUE THREAD

**Issue by se8820726** [kornrunner/php-keccak#6]
hi

I got wrong result after keccak256 hash of this string by using your library:
`0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080`
this is my code:

```
use kornrunner\Keccak;

$signing_data = 'ec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080';
$signing_hash = Keccak::hash($signing_data, 256);

echo $signing_hash; // result: c16ddf07b0b8f8e3f0c84ada692e0e40322d848cfccaa3dbebec044fb9ede56a
```
but according to [this url](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) it must get me this result:
`0xdaf5a779ae972f972197303d7b574746c7ef83eadac0f2791ad23db92e4c8e53`

what is wrong ?

I asked a question [here](https://ethereum.stackexchange.com/questions/59892/problem-in-generating-keccak256-hash-of-signing-data). please see it.

**Comment by kornrunner** [comment]
That is the correct hash for given input string. You can double check [here](https://keccak-256.cloxy.net/) or [here](https://emn178.github.io/online-tools/keccak_256.html)

Based on your URL you're actually looking for [kornrunner/php-ethereum-offline-raw-tx](https://github.com/kornrunner/php-ethereum-offline-raw-tx) instead, following code reproduces the example from given page:

```php
<?php

require_once 'vendor/autoload.php';

use kornrunner\Ethereum\Transaction;

$nonce    = '09';
$gasPrice = dechex(20 * pow(10,9));
$gasLimit = dechex(21000);
$to       = '3535353535353535353535353535353535353535';
$value    = dechex(pow(10,18));
$chainId  = 1;

$privateKey = '4646464646464646464646464646464646464646464646464646464646464646';

$transaction = new Transaction ($nonce, $gasPrice, $gasLimit, $to, $value);
echo $transaction->getRaw ($privateKey, $chainId);
// f86c098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a76400008025a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83
```
